const ACTION_TYPES = {
  SET_USER: "SET_USER",
  GET_USER_PROFILE: "GET_USER_PROFILE",
  IS_SIGNED_IN: "IS_SIGNED_IN",

  GET_BOARDS_ARRAY: "GET_BOARDS_ARRAY",
  ADD_BOARD: "ADD_BOARD",
};

export default ACTION_TYPES;
